#! /bin/bash

#-> SENDS STRING TO STDERR
#-> TAKES A STRING AS ARGS
#-> RETURNS STATUS OF ECHO
function errcho() {
	local str="${*}"
	>&2 echo "ERROR >>>> ${str}"
	return $?
}

debug "Sourced file: ${BASH_SOURCE[0]}"
debug
