#! /bin/bash

#-> 
#-> 
#-> 
function funcEnd() {
	local errcode
	local retval="${*}"
	local str="END FUNCTION ${FUNCNAME[1]}"

	if [ ! -z "${retval}" ] ; then
		str="${str} with errcode of $retval"
	fi

	((DEBUG_DEPTH--))

	debug "${str}" ; errcode=$?
	return $errcode
}

debug "Sourced file: ${BASH_SOURCE[0]}"
debug
