#! /bin/bash

#-> PRIMARY INITIALISATION SYSTEM FOR ALL SCRIPTS
#-> RELIES ON $FUNC HAVING BEEN SET BY THE SCRIPT CALLING IT
source ${FUNC}debug
source ${FUNC}errcho
source ${FUNC}loader

#-> CHECK FOR A PROJECT_FUNCTIONS FOLDER TO RUN THROUGH THE LOADER
if [ -d "${FUNC}../project_functions/" ] ; then
	FUNC="${FUNC}../project_functions/"
	source ${FUNC}
fi

debug "end ${FUNC}init"
debug
debug

