#! /bin/bash

#-> PRIMARY INITIALISATION SYSTEM FOR ALL SCRIPTS
#-> RELIES ON $_ROOT HAVING BEEN SET BY THE SCRIPT CALLING IT, POINTING TO THE DIRECTORY CONTAINING init
_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source ${_ROOT}/debug
source ${_ROOT}/errcho
source ${_ROOT}/loader

loader "${_ROOT}"

debug "end ${_ROOT}init"
debug
debug
