#! /bin/bash
#-> DECLARE THE ARRAY WHICH WILL CONTAIN THE LIST OF FILES TO PASS TO SHELLCHECK
declare -a files
#-> ADD NON *.sh CORE FILES
files+=(./debug)
files+=(./errcho)
files+=(./funcEnd)
files+=(./funcStart)
files+=(./init)
files+=(./loader)
files+=(./skeleton)
files+=(./test)
files+=(./shellcheck)

#-> ADD REMAINING FUNCTION FILES ENDING IN .sh
files+=(./*.sh)
files+=(./*/*.sh)
files+=(./*/*/*.sh)
files+=(./*/*/*/*.sh)

shellcheck --color=always --shell=bash "${files[@]}" "${@}"
