#! /bin/bash

#-> SKELETON FOR PACKAGE-FROM-FILE INSTALLATION. CALLS FUNCTION TO DISCOVER PACKAGE MANAGER AND THEN CALLS THE INSTALL FUNCTION FOR THAT MANAGER.
#-> TAKES THE FOLLOWING OPTIONAL ARGS AS INPUT, WHICH WILL BE CONVERTED INTO THE APPROPRIATE ARGS FOR THE LOCAL PACKAGE MANAGER
#->  --unattended
#->  --verbose
#-> TAKES A LIST OF PACKAGES AS THE FINAL ARGUMENT
#-> RETURNS THE EXIT STATUS OF THE package_${PACKAGE_MANAGER}_install FUNCTION, OR 1 IF IT FAILS TO FIND A SUPPORTED PACKAGE MANAGER.
function package_installFromFile() {
	debug "BEGIN FUNCTION ${FUNCNAME[0]}"
	if package_getManager ; then
#		if [[ ! -z "${PACKAGE_MANAGER}" ]] ; then
			package_${PACKAGE_MANAGER}_installFromFile "$@"
			errcode=$?

			debug "END FUNCTION ${FUNCNAME[0]}"

			return ${errcode}
#		fi
#		debug "END FUNCTION ${FUNCNAME[0]}"
#		return 1
	else
		debug "END FUNCTION ${FUNCNAME[0]}"
		return 1
	fi
}
